apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sample-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      web: sample
  template:
    metadata:
      labels:
        web: sample 
    spec:
      containers:
        - image: ravikv123/webserver:newwebserver
          name: sample-cont
          ports:
            - containerPort: 80


