apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-app-rs
spec:
  replicas: 5
  selector: 
    matchlabels:
      web: app
  template: #Define the pod definition
    metadata:
      labels:
        web: app
    spec:
      containers:
        - name: sample-cont
          image: ravikv123/apachewebserver:apache-cust
          ports:
            - containerPort: 80
