apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-rs
spec:
  replicas: 5
  selector: 
    matchLabels:
      web: app
  template: #Define the pod definition
    metadata:
      labels:
        web: app
    spec:
      containers:
        - name: sample-cont
          image: ravikv123/webserver:newwebserver
          ports:
            - containerPort: 80
